---
- name: Include installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
  when: uv_install

- debug: var=_uv_venvs

- name: Include task files
  ansible.builtin.include_tasks:
    file: venv.yml
  loop: "{{ _uv_venvs }}"
  loop_control:
    loop_var: venv
    label: "{{ venv.path }}"
  vars:
    uv_action: "{{ 'sync' if venv.strategy == 'sync' else 'install -r' }}"
    uv_upgrade_flag: "{{ '--upgrade' if (venv.strategy == 'install' and venv.upgrade) else '' }}"
