---
- name: Try to fetch current uv version
  ansible.builtin.command: "{{ uv_dir }}/uv --version"
  register: uv_check
  changed_when: false
  failed_when: false

- name: Set current and target version
  ansible.builtin.set_fact:
    uv_current_version: "{{ (uv_check.stdout | regex_search('uv ([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1') | first) if uv_check.rc == 0 else '0.0.0' }}"
    uv_target_version: "{{ (lookup('ansible.builtin.url', uv_latest_version_api_url) | from_json).tag_name if uv_version == 'latest' else uv_version }}"

- name: Display status
  ansible.builtin.debug:
    msg: "uv {{ uv_current_version }}{{ ' (latest)' if uv_version == 'latest' }} is already installed, skipping remaining tasks"
  when: uv_current_version == uv_target_version

- name: Ensure uv is available
  when: uv_current_version != uv_target_version
  block:
    - name: "Download tarball from {{ uv_release_url }}"
      ansible.builtin.get_url:
        url: "{{ uv_release_url }}"
        checksum: "sha256:{{ uv_release_url }}.sha256"
        dest: /tmp/uv.tar.gz
        mode: "0644"

    - name: "Unarchive binaries in {{ uv_dir }}"
      ansible.builtin.unarchive:
        src: /tmp/uv.tar.gz
        dest: "{{ uv_dir }}"
        remote_src: true
        extra_opts:
          - "--strip-components=1"
      become: true

    - name: Clean up tarball
      ansible.builtin.file:
        path: /tmp/uv.tar.gz
        state: absent

    - name: Display status
      ansible.builtin.debug:
        msg: "Installed uv {{ uv_target_version }}"
