---
- name: Import base venv task
  ansible.builtin.import_tasks: venv_base.yml

- name: Read requirements checksum tracker
  ansible.builtin.slurp:
    src: "{{ req_file }}.sha256"
  register: _tracker_content
  failed_when: false
  changed_when: false

- name: Install requirements into virtualenv  # noqa no-changed-when
  ansible.builtin.command:
    cmd: >
      {{ uv_bin_path | quote }}
      pip install
      --python {{ venv.path | quote }}
      -r {{ req_file | quote }}
  when: >-
    _tracker_content.content is not defined
    or
    (_tracker_content.content | b64decode | trim) != req_checksum
  register: _install_result
  environment: "{{ venv.environment }}"

- name: Update requirements checksum tracker  # noqa no-handler
  ansible.builtin.copy:
    content: "{{ req_checksum }}"
    dest: "{{ req_file }}.sha256"
    mode: '0644'
  when: _install_result is changed
