---
- name: Ensure virtualenv is available
  ansible.builtin.command:
    cmd: >
      {{ uv_bin_path }} venv {{ venv.path | quote }}
    creates: "{{ venv.path }}"
  environment: "{{ venv.environment }}"

# TODO: assert if state exists etc
- name: "Include tasks for state {{ venv.state }}"
  ansible.builtin.include_tasks:
    file: "venv_state_{{ venv.state }}.yml"
