---
- name: Import base venv task
  ansible.builtin.import_tasks: venv_base.yml

- name: Check requirements sync status in venv  # noqa no-changed-when
  ansible.builtin.command:
    cmd: >
      {{ uv_bin_path | quote }}
      pip sync
      --python {{ venv.path | quote }}
      --check
      {{ req_file }}
      --output-format=json
  register: _uv_sync_status
  changed_when: false
  failed_when: false
  environment: "{{ venv.environment }}"

- name: Sync requirements in venv  # noqa no-changed-when
  ansible.builtin.command:
    cmd: >
      {{ uv_bin_path | quote }}
      pip sync
      --python {{ venv.path | quote }}
      {{ req_file }}
  when: (_uv_sync_status.stdout | from_json).changes | length > 0
  register: _uv_synced
  environment: "{{ venv.environment }}"

- name: Update requirements checksum tracker  # noqa no-handler
  ansible.builtin.copy:
    content: "{{ req_checksum }}"
    dest: "{{ req_file }}.sha256"
    mode: "0644"
  when: _uv_synced is changed
