---
- name: Ensure virtualenv is available
  ansible.builtin.command:
    cmd: >
      {{ uv_bin_path | quote }}
      venv
      {{ venv.path | quote }}
    creates: "{{ venv.path }}"
  environment: "{{ venv.environment }}"

- name: Ensure requirements file is available
  ansible.builtin.copy:
    content: "{{ venv.requirements }}"
    dest: "{{ req_file }}"
    mode: "0640"
